### ISSUE TITLE
Figure out what to do when a domain redirects to a subdomain when starting to crawl 

### ISSUE THREAD

**Issue by buren** [buren/wayback_archiver#15]

**Comment by chlorophyll-zz** [comment]
I think you closed this with #27 
To archive the origin pages first, you could crawl all referenced ressources from one page even on a subdomain to archive a coherent complete page, but stay to the origin source of the referenced ressources and crawl from there on. 
What you are accomplishing with the --crawl option is sometimes anyway a complete domain archival.
